version: "3.9"

services:
  web:
    build: .
    container_name: "${PROJECT_NAME}_web"
    ports:
      - "5000:5000"
    volumes:
      - "./peach-blog/posts:/peach-blog/posts"
    restart: always
    networks:
        extnetwork:
    depends_on: 
        - mysql      
  mysql:
      image: mysql:$MYSQL_TAG
      container_name: "${PROJECT_NAME}_mysql"
      command: mysqld --default-authentication-plugin=mysql_native_password
      environment: 
          MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
          MYSQL_USER: $DB_USER
          MYSQL_PASSWORD: $DB_PASSWORD
          MYSQL_DATABASE: $DB_NAME
      ports: 
          - $DB_PORT
      restart: always
      networks:
          extnetwork:
              ipv4_address: 192.18.2.2

networks:
    extnetwork:
        ipam:
            config:
                - subnet: 192.18.2.0/24
                  gateway: 192.18.2.1