"""empty message

Revision ID: d7c27d402972
Revises: 00b17ef8f166
Create Date: 2018-11-07 09:20:09.092514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c27d402972'
down_revision = '00b17ef8f166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post2tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'post2tags', 'tags', ['tag_id'], ['id'])
    op.add_column('users', sa.Column('level', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_constraint(None, 'post2tags', type_='foreignkey')
    op.drop_constraint(None, 'post2tags', type_='foreignkey')
    # ### end Alembic commands ###
